project:
  type: website
  output-dir: docs

website:
  title: "KAIRI MEECHOOVET"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Marketing Analytics in Gaming & Esports"
        href: marketing-analytics.qmd
      - text: "Bronco Esports"
        href: Bronco Esports.qmd
      - text: "Résumé"
        href: resume.qmd


format:
  html:
    theme: [flatly, theme.scss]
    toc: true

