---
title: "Marketing Analytics In Gaming and Esports"
listing: 
  contents: listings
  type: grid
  categories: true
  sort: 
    - "index desc"
---

Below are selected projects for the data-driven work I've done related to gaming and Esports. I've combined my passion for competitive gaming and social media with marketing analytics to uncover insights, optimize strategies, and drive engagement for the communities I work with. Whether analyzing social media trends for esports orgs, measuring in-game ad performance, or tracking tournament viewership metrics, I turn raw data into a *victory*.

## What You’ll Find

- **Campaign Performance Analysis:** Measuring ROI for gaming brands, sponsorships, and influencer collaborations. 
- **Data Visualization:** Dashboards tracking Tiwtch viewership, social engagement, and in-game purchase behavior.
- **Marketing Mix & Attribution:** Breaking down which digital platform (Discord, Twitter, TikTok) drive the most conversions for different campaigns.
- **Customer & Market Insights:** Using analytics to better understand our target audience (the gamers) and hwat keeps them playing our game or engaging with our products. 

---